### ISSUE TITLE
Option to only install hugo on npm --production 

### ISSUE THREAD

**Issue by sean-pwd** [dominique-mueller/hugo-installer#39]
My current issue is I have set up my hugo projects so that dependencies which are not required on netlify (e.g. linting or formatting or hugo) are installed as devDependencies. This way my netlify build is sped up. 

The problem is that I have hugo-installer set up as a postinstall script and netlify tried to run it, forcing me to have hugo-installer installed as a normal dependency.  (netlify is configured to pass the --production parameter)

I have looked into disabling postinstall on production and I cant find a clean solution, without adding another js script to the project. 

Would it be easier to include this script in hugo-installer and provide the option e.g. --development so that if hugo-installer is run in the production environment (which only happens if the user specifies this environment) it will exit without running any code.

**Comment by dominique-mueller** [comment]
I haven't had the chance yet to use Netflity, but I understand that you want to simulate Hugo being a `dependency` instead of a `devDependency`, which is something npm doesn't support out of the box for `postinstall` scripts.

I don't think that adding this feature makes sense in the context of hugo-installer, I instead see it as a separate concern that should be handled within the npm script itself.

A quick research brought me to npm packages like [if-env](https://github.com/ericclemmons/if-env) or [per-env](https://github.com/ericclemmons/per-env), have you tried to use on of those as a solution?

**Comment by sean-pwd** [comment]
Thanks Dominique, I will check out those two packages and report back.

**Comment by dominique-mueller** [comment]
Any luck? :)

**Comment by sean-pwd** [comment]
Yes

There is a npm package called if-env which allows you to only run the hugo postinstall on development (Which is the default environment). 

On the other hand, only the initial netlify build is slowed down, everything is cached for subsequent builds
