### ISSUE TITLE
hugo-installer fails on macOS as of v0.102.0

### ISSUE THREAD

**Issue by kevinjcharles** [dominique-mueller/hugo-installer#49]
The ARM-based Hugo binaries for Macintosh have been replaced by Universal binaries as of v0.102.0.

hugo-installer breaks when attempting to install any Hugo version above v0.101.0.

From the Hugo v0.102.0 release notes:

> The MacOS archives have been replaced with universal/fat binaries that works on all MacOS platforms, named *macOS-universal.tar.gz.

[https://github.com/gohugoio/hugo/releases/tag/v0.102.0](https://github.com/gohugoio/hugo/releases/tag/v0.102.0)

**Comment by itsdevdom** [comment]
Huge thanks for notifying me about this. The Hugo team already tried introducing universal / fat binaries in the past but reverted the change due to a broken release (see https://github.com/dominique-mueller/hugo-installer/issues/43).

The latest release **[4.0.0](https://github.com/dominique-mueller/hugo-installer/releases/tag/4.0.0)** is now aware of the new binaries. Note that at least NodeJS 14 is required now (thus the major version bump). Enjoy! :tada:

Also, feel free to re-open or open a new issue if anything is not working as intended; I don't have a testing setup with MacOS here but the CI is at least happy on MacOS 12 (see [job](https://github.com/dominique-mueller/hugo-installer/actions/runs/3046626972/jobs/4909679904)).
